### ISSUE TITLE
Conflict with module “MekanismMoreMekaSuitModules”

### ISSUE THREAD

**Issue by Candy-sky** [kotlin-programmer/Ice_and_Fire_RLCraft#35]
This PR caused this problem, please fix it.
https://github.com/kotlin-programmer/Ice_and_Fire_RLCraft/pull/29

[crash-2025-05-16_15.42.55-client.txt](https://github.com/user-attachments/files/20260441/crash-2025-05-16_15.42.55-client.txt)

**Comment by kotlin-programmer** [comment]
Fixed locally. This will be addressed in the upcoming release.

**Comment by Candy-sky** [comment]
Thank you very much !

**Comment by Xplodin** [comment]
was this fixed in a release? Im also getting the same crash

**Comment by Candy-sky** [comment]
> was this fixed in a release? Im also getting the same crash

In fact, it hasn't been fixed yet. This error still exists. It's just that I haven't had time to use it recently, so...

**Comment by kotlin-programmer** [comment]
Fixed in version 2.1.7.

**Comment by Xplodin** [comment]
wait im on that version, and it still crashes

**Comment by Xplodin** [comment]
https://mclo.gs/KYvIGcj
